services:
  queue-mgr:
    container_name: queue-mgr
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '5010:5010'
    restart: always
    env_file:
      - ../.env.production
    command: [ 'uvicorn', 'app:app', '--host', '0.0.0.0', '--port', '5010', '--workers', '4' ]
