services:
  queue-mgr:
    container_name: queue-mgr
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '5010:5010'
    restart: always
    depends_on:
      - queue-mgr-postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@queue-mgr-postgres:5432/queue_mgr_db
      ENVIRONMENT: local
    command: [ 'uvicorn', 'app:app', '--host', '0.0.0.0', '--port', '5010' ]

  queue-mgr-postgres:
    container_name: queue-mgr-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: queue_mgr_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
