name: Deploy Queue Mgr Microservice (UAT Auto)

on:
  push:
    branches:
      - main

jobs:
  deploy-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_AWS_UAT_PRIVATE_KEY }}

      - name: Update and Restart Microservice on UAT
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.INTEGRATION_EC2_IP }} << 'EOF'
            bash /home/ec2-user/update_microservice.sh git@github.com:SWE5001-Team-Public/queuetopia-queue-mgr.git /home/ec2-user/queuetopia-queue-mgr
            cd /home/ec2-user/queuetopia-queue-mgr
            bash ./scripts/up.sh --dev
          EOF
