name: Deploy Queue Mgr Microservice (Production Manual)

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Start Auto Scaling Group Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name QueuetopiaSvcMgrASG \
            --preferences '{"SkipMatching": false}' \
            --region ap-southeast-2
